[package]
name = "sse-json"
version = "0.0.1"
authors = ["Bevan Hunt <bevan@bevanhunt.com>"]
edition = "2018"
license = "MIT"

[dependencies]
actix-rt = "1.0.0"
actix-web = "2.0.0-rc"
futures = "0.3.1"
tokio = "0.2.4"
sse-actix-web="0.5.3"
serde = "1.0.103"
serde_json = "1.0.44"
serde_derive = "1.0.103"
json = "0.12.0"
