[package]
name = "sse-json"
version = "0.0.1"
authors = ["Bevan Hunt <bevan@bevanhunt.com>"]
edition = "2018"
license = "MIT"

[dependencies]
actix = "0.9.0"
actix-rt = "1.0.0"
actix-web = "2.0.0"
actix-cors = "0.2.0"
futures = "0.3.1"
tokio = "0.2.4"
sse-actix-web ="0.6.1"
ws-actix-web = "0.1.6"
serde = "1.0.103"
serde_json = "1.0.44"
serde_derive = "1.0.103"
json = "0.12.0"
sled = "0.30.3"
envy = "0.4.0"
awc = "1.0.1"
